syntax = "proto3";
package com.proto.api;

message StringColumn {repeated string values = 1;}
message IntColumn    {repeated int32  values = 1;}
message LongColumn   {repeated int64  values = 1;}
message FloatColumn  {repeated float  values = 1;}
message DoubleColumn {repeated double values = 1;}
message BoolColumn   {repeated bool   values = 1;}
message BytesColumn  {repeated bytes  values = 1;}

message FeatureType {
  oneof values {
    StringColumn string_values = 1;
    IntColumn    int_values = 2;
    LongColumn   long_values = 3;
    FloatColumn  float_values = 4;
    DoubleColumn double_values = 5;
    BoolColumn   bool_values = 6;
    BytesColumn  bytes_values = 7;
  }
}

message FeatureColumn{
  repeated FeatureType values = 1;
}

message PutRequest {
  repeated string entity_keys = 1;
  map<string, FeatureColumn> columns = 3;
}

message GetRequest{
  repeated string entity_keys = 1;
  repeated string features = 2;
}

message GetResponse {
  repeated string entity_keys = 1;
  map<string, FeatureColumn> columns = 3;
}

message PutResponse {
  uint32 written_entities = 1;
  bool success = 2;
}

service FeatureStore {
  rpc Put(PutRequest) returns (PutResponse);
  rpc Get(GetRequest) returns (GetResponse);
}

message EntityRecordRedis{
  string key = 1;
  bytes value = 2;
}

message FeatureTypeSingle {
  oneof values {
    string string_value = 1;
    int32 int_value = 2;
    int64 long_value = 3;
    float float_value = 4;
    double double_value = 5;
    bool bool_value = 6;
    bytes bytes_value = 7;
  }
}

message RedisPayload{
  map<string, FeatureTypeSingle> features = 1;
}


